package:
  name: conda-build
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  # WARNING: git_url ignores uncommitted code
  git_url: ../

build:
  script: python -m pip install . -vv
  entry_points:
    - conda-build = conda_build.cli.main_build:main
    - conda-convert = conda_build.cli.main_convert:main
    - conda-debug = conda_build.cli.main_debug:main
    - conda-develop = conda_build.cli.main_develop:main
    - conda-index = conda_build.cli.main_index:main
    - conda-inspect = conda_build.cli.main_inspect:main
    - conda-metapackage = conda_build.cli.main_metapackage:main
    - conda-render = conda_build.cli.main_render:main
    - conda-skeleton = conda_build.cli.main_skeleton:main

requirements:
  build:
    - git
  host:
    - python
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
  run:
    - beautifulsoup4
    - chardet
    - conda >=4.13
    - conda-index
    - filelock
    - jinja2
    - packaging
    - patchelf                     # [linux]
    - patch >=2.6                  # [not win]
    - m2-patch >=2.6               # [win]
    - pkginfo
    - psutil
    - py-lief                      # [not win]
    - python
    - pyyaml
    - requests
    - six
    - glob2 >=0.6
    - pytz
    - tomli                        # [py<311]
    - tqdm
    - conda-package-handling >=1.3
    - python-libarchive-c
  run_constrained:
    - conda-verify  >=3.0.2

test:
  files:
    - test_bdist_conda_setup.py
  imports:
    # high-level import
    - conda_build
  commands:
    # builtin subcommands
    - conda build --help
    - conda convert --help
    - conda develop --help
    - conda index --help
    - conda inspect --help
    - conda inspect linkages --help  # [unix]
    - conda inspect objects --help  # [osx]
    - conda metapackage --help
    - conda render --help
    - conda skeleton --help
    - conda debug --help
    # test that conda sees entry points appropriately in help
    - conda --help
    # bdist_conda
    - python test_bdist_conda_setup.py bdist_conda --help

about:
  home: https://github.com/conda/conda-build
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Canary release of conda-build
